### ISSUE TITLE
Doesn't work with `ctheorems`

### ISSUE THREAD

**Issue by EricWay1024** [Jollywatt/typst-wordometer#1]
Hi, thank you for developing this tool. I've been working on my math report which requires a word count, but this package doesn't seem to work with another package, `ctheorems`, which I also use. A minimal reproducible error is as follows,

```typst
#import "@preview/wordometer:0.1.0": word-count
#import "@preview/ctheorems:1.1.0": *
#let theorem = thmbox(
  "theorem",
  "Theorem",
)

#word-count(total => [
  #theorem[
    A theorem.
  ]
  The number of words in this block is #total.words
  and there are #total.characters letters.
])
```
The CLI complier (version `typst 0.10.0 (70ca0d25)`) produces the error:
```
error: type none has no method `func`
    ┌─ @preview/wordometer:0.1.0\src\lib.typ:149:24
    │
149 │   let fn = repr(content.func())
    │                         ^^^^
```

Any ideas how I can get this working? Thanks a lot.

**Comment by Jollywatt** [comment]
Aha, thanks for that. This was happening because `theorem` is a figure with a caption that has the value `none`, which I forgot to handle (normally, captionless figures don’t even have a `caption` field).

This is fixed in 0f1eae6. I’ll make a PR to update the official package now.

**Comment by EricWay1024** [comment]
Hi, thank you so much for the quick fix. It is working properly now. Just a quick reminder that the manual link in the README seems to be 404 now. Thanks again for your work.

**Comment by Jollywatt** [comment]
Ah, forgot to push the v0.1.1 tag - thanks again!
