### ISSUE TITLE
Deprecation warning on locate

### ISSUE THREAD

**Issue by akshaybabloo** [Jollywatt/typst-wordometer#8]
In the new typst 0.12.0-rc1, I started getting this warnings (image below)

![image](https://github.com/user-attachments/assets/0be801ed-ef45-4c09-990f-361f19123790)

**Comment by akshaybabloo** [comment]
I think that did not fix, I am still getting this

![image](https://github.com/user-attachments/assets/c6c6b354-a7dc-4f0e-892a-ea8aad83ddf2)

**Comment by Jollywatt** [comment]
Whoops! irresponsible maintainer alert

**Comment by Jollywatt** [comment]
Somehow when I released v0.1.3, it didn't actually include the commits that implemented the fix… so I've had to release them as v0.1.4, see https://github.com/typst/packages/pull/1197 🤡
